"""jobs/qr/qr_generate.py — QR code generation with inline-delivery support."""
import io
from datetime import datetime
from pathlib import Path

import qrcode

from jobs.email_job.brevo_send import send_email

QR_OUTPUT_DIR = Path(__file__).resolve().parents[2] / "data" / "qr"


def generate_qr(content: str) -> tuple[str, bytes]:
    """Generate a QR code PNG for the given content. Returns (file_path, png_bytes)."""
    QR_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    qr = qrcode.QRCode(
        version=None,
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=10,
        border=4,
    )
    qr.add_data(content)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filepath = str(QR_OUTPUT_DIR / f"qr_{timestamp}.png")
    img.save(filepath)

    buf = io.BytesIO()
    img.save(buf, format='PNG')
    png_bytes = buf.getvalue()

    return filepath, png_bytes


def send_qr_email(to_email: str, to_name: str, content: str, png_bytes: bytes) -> bool:
    """Email the QR code PNG as an attachment via Brevo."""
    result = send_email(
        to_email=to_email,
        to_name=to_name,
        subject=f"QR Code — {content[:40]}",
        text_body=f"QR code for: {content}\n\nGenerated by Watson.",
        attachments=[{"name": "qr_code.png", "content": png_bytes}],
    )
    if not result["success"]:
        raise RuntimeError(f"Brevo send failed: {result['error']}")
    return True


def run(message: str = None) -> str:
    if not message or not message.strip():
        return "Please provide a URL or text for the QR code."
    content = message.strip().split()[-1]
    try:
        filepath, _ = generate_qr(content)
        return f"QR code generated for: {content}\nSaved to: {filepath}"
    except Exception as exc:
        return f"QR generation failed: {exc}"
