"""jobs/qr/qr_generate.py — QR code generation with inline-delivery support."""
import io
import os
import smtplib
from datetime import datetime
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

import qrcode
from dotenv import load_dotenv

QR_OUTPUT_DIR = Path(__file__).resolve().parents[2] / "data" / "qr"


def generate_qr(content: str) -> tuple[str, bytes]:
    """Generate a QR code PNG for the given content. Returns (file_path, png_bytes)."""
    QR_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    qr = qrcode.QRCode(
        version=None,
        error_correction=qrcode.constants.ERROR_CORRECT_H,
        box_size=10,
        border=4,
    )
    qr.add_data(content)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filepath = str(QR_OUTPUT_DIR / f"qr_{timestamp}.png")
    img.save(filepath)

    buf = io.BytesIO()
    img.save(buf, format='PNG')
    png_bytes = buf.getvalue()

    return filepath, png_bytes


def send_qr_email(to_email: str, to_name: str, content: str, png_bytes: bytes) -> bool:
    """Email the QR code PNG as an attachment using Watson SMTP credentials."""
    load_dotenv(Path(__file__).resolve().parents[2] / ".env")

    smtp_host = 'smtp.gmail.com'
    smtp_port = 587
    smtp_user = os.environ['WATSON_GMAIL_ADDRESS']
    smtp_pass = os.environ['WATSON_GMAIL_APP_PASSWORD']
    from_addr = os.environ.get('WATSON_FROM_ADDRESS', smtp_user)

    msg = MIMEMultipart()
    msg['From'] = f"Watson <{from_addr}>"
    msg['To'] = f"{to_name} <{to_email}>"
    msg['Subject'] = f"QR Code — {content[:40]}"

    msg.attach(MIMEText(f"QR code for: {content}\n\nGenerated by Watson.", 'plain'))

    attachment = MIMEImage(png_bytes, name='qr_code.png')
    attachment.add_header('Content-Disposition', 'attachment', filename='qr_code.png')
    msg.attach(attachment)

    with smtplib.SMTP(smtp_host, smtp_port) as server:
        server.starttls()
        server.login(smtp_user, smtp_pass)
        server.send_message(msg)

    return True
