"""jobs/dev/git_tools.py — Watson git history, manual fix detection, and diff tools."""
import logging
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
BUILT_BY_MODELS = {"qwen2.5-coder", "claude-sonnet", "watson"}

log = logging.getLogger(__name__)


def get_recent_commits(n: int = 10) -> list:
    from git import Repo
    try:
        repo = Repo(str(REPO))
        commits = []
        for commit in repo.iter_commits("HEAD", max_count=n):
            commits.append({
                "hash": commit.hexsha[:8],
                "message": commit.message.strip().splitlines()[0],
                "author": commit.author.name,
                "date": commit.committed_datetime.isoformat(),
            })
        return commits
    except Exception as exc:
        log.error("get_recent_commits failed: %s", exc)
        return []


def get_diff(commit_hash: str) -> str:
    from git import Repo
    try:
        repo = Repo(str(REPO))
        commit = repo.commit(commit_hash)
        if commit.parents:
            return repo.git.diff(commit.parents[0].hexsha, commit.hexsha)
        return repo.git.show(commit.hexsha)
    except Exception as exc:
        log.error("get_diff failed: %s", exc)
        return f"Error: {exc}"


def get_file_history(file_path: str) -> list:
    from git import Repo
    try:
        repo = Repo(str(REPO))
        commits = []
        for commit in repo.iter_commits("HEAD", paths=file_path, max_count=20):
            commits.append({
                "hash": commit.hexsha[:8],
                "message": commit.message.strip().splitlines()[0],
                "author": commit.author.name,
                "date": commit.committed_datetime.isoformat(),
            })
        return commits
    except Exception as exc:
        log.error("get_file_history failed: %s", exc)
        return []


def find_manual_fixes() -> list:
    from git import Repo
    try:
        repo = Repo(str(REPO))
        manual = []
        for commit in repo.iter_commits("HEAD", max_count=100):
            msg = commit.message.strip().lower()
            is_model_built = any(model in msg for model in BUILT_BY_MODELS)
            is_skill_commit = msg.startswith("skill:") or "generated by" in msg
            if not is_model_built and not is_skill_commit:
                if any(kw in msg for kw in ("fix:", "hotfix", "manual", "patch", "bug")):
                    manual.append({
                        "hash": commit.hexsha[:8],
                        "message": commit.message.strip().splitlines()[0],
                        "author": commit.author.name,
                        "date": commit.committed_datetime.isoformat(),
                    })
        return manual
    except Exception as exc:
        log.error("find_manual_fixes failed: %s", exc)
        return []


def run(message: str = None) -> str:
    commits = get_recent_commits(5)
    if not commits:
        return "No commits found."
    lines = ["Recent commits:\n"]
    for c in commits:
        lines.append(f"  {c['hash']}  {c['date'][:10]}  {c['message']}")
    return "\n".join(lines)
